#!/bin/bash
# Script to copy resized images to GitHub Pages directory

SOURCE_DIR="/Users/briandizio/Documents/2023-Now/Golden Enterprise Solutions/Solutions/The Portraits/src/core/resized_paintings"
DEST_DIR="/Users/briandizio/Documents/2023-Now/Golden Enterprise Solutions/Solutions/golden-enterprises-paintings/paintings"

echo "Copying resized images..."
cp "$SOURCE_DIR/The_Portraits_III.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XIV.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XV.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XVI.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XVII.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XVIII.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XIX.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XX.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXI.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXII.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXIII.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXIV.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXV.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXVI.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXVII.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXVIII.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXX.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXXI.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXXII.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXXIV.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXXV.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXXVIII.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XXXIX.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XL.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XLI.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XLII.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XLIII.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XLIV.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XLVI.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XLVII.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XLVIII.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_XLIX.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_L.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_LI.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_LII.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_LIV.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_LV.png" "$DEST_DIR/"
cp "$SOURCE_DIR/The_Portraits_LVI.png" "$DEST_DIR/"
echo "Done! Now commit and push to GitHub."
